version: '3'

services:
    nginx:
        image: nginx:latest
        ports:
            - "8080:80"
        volumes:
            - ./docker/nginx/default.conf:/etc/nginx/conf.d/default.conf
    fpm:
        build:
            dockerfile: ./docker/Dockerfile
            context: .
        volumes:
            -  ./:/var/www/html
    postgres:
        image: postgres:11.15-alpine3.15
        environment:
            - POSTGRES_USER=postgres
            - POSTGRES_PASSWORD=postgres
            - POSTGRES_DB=test_case
        volumes:
            - postgres:/var/lib/postgresql/data
        ports:
            - "54321:5432"

volumes:
    postgres:
